channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.0
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.2.1
  - pandas==2.2.3
  - psutil==7.1.0
  - pyarrow==18.1.0
  - scikit-learn==1.7.2
  - scipy==1.16.2
name: mlflow-env
