name: CI Pipeline (Local)

on: [push]

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install DVC
        run: |
          pip install dvc    

      - name: Run DVC pipeline
        run: |
          dvc repro

      - name: Run unit tests for model
        run: |
          python -m unittest tests/test_model.py

      - name: Run unit tests for Flask app
        run: |
          python -m unittest tests/test_flask_app.py

      - name: Promote model to production (Local)
        if: success()
        run: |
          python scripts/promote_model.py

      - name: Build Docker image locally
        run: |
          docker build -t mlops-local-app:latest .

      - name: Verify Docker image
        run: |
          docker images mlops-local-app

      - name: Run container (optional test)
        run: |
          docker run -d -p 5000:5000 mlops-local-app:latest
          sleep 10
          docker ps

      - name: Stop and remove container (cleanup)
        if: always()
        run: |
          docker stop $(docker ps -q --filter ancestor=mlops-local-app:latest) || true
          docker rm $(docker ps -a -q --filter ancestor=mlops-local-app:latest) || true
